### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ghost** [wwyaiykycnf/e621dl#44]
It will not work no matter what

http://prntscr.com/hgy0an

**Comment by Wulfre** [comment]
That usually happens when the user-agent gets banned from e621. I'm not able to test it right now, but you should be able to change the version variable in `downloader.py` to fix it temporarily until it get banned again. There is something that e621 doesn't like about how this script works, but I've had good luck with my own fork.

**Comment by DatDraggy** [comment]
Edit support.py and downloader.py 
Replace `version = 'e621dl ' + VERSION + ' (by wwyaiykycnf)` with `version = 'e621dl/' + VERSION + ' (by YOUR_e621_USERNAME_HERE)'`

This is _required_ by the e621 api rules and we should put it in the config.
If you don't have a username, choose your github name

**Comment by ghost** [comment]
Where do I find thosek?

**Comment by ghost** [comment]
I changed them, now it stays open for a while with 'running e621dl' and then it turns off

**Comment by DatDraggy** [comment]
Haven't used this in a while
Maybe it downloaded the files? I'll check what it's supposed to do later when I got time
